### ISSUE TITLE
You can collect passengers with any vehicle in my case i try with car t20 and finish job in 10min! Try to fix this

### ISSUE THREAD

**Issue by Tinky124** [propstg/esx-blarglebus#11]
You can collect passengers with any vehicle in my case i try with car t20 and finish job in 10min! Try to fix this

**Comment by propstg** [comment]
Hey, thanks for the report.

How would I go about recreating this? Is it just something simple like "start bus route and get in a vehicle that isn't the bus?"

Thanks!

**Comment by Tinky124** [comment]
@propstg Yes like try to make so it pop up message : Get in bus to collect passengers and 
if the person uses another vehicle so he cant collect passenger without bus ! Only with bus he can collect..

**Comment by propstg** [comment]
I pushed a change that should display a message and prevent the player from picking up passengers when they aren't in the bus. Let me know if this doesn't fix it on your end or if you have any more issues!

**Comment by Tinky124** [comment]
@propstg  Fixed the issue good job bro!! Thanks for support closing this issue if i will another i will report..

**Comment by propstg** [comment]
Glad to hear it worked. Thanks!
