### ISSUE TITLE
Allow routes with different ending terminals / Menu to choose between routes in same location

### ISSUE THREAD

**Issue by jwbjnwolf** [propstg/esx-blarglebus#13]
Love how easy it is to modify this for your own routes. However I don't want to have to drive back to Dashound, where the route started to complete the job for the route that is supposed to of finished at the fuel station in Paleto Bay.

Also as an addition, have the ability to chose between routes/lines that are grouped together like the metro routes instead of being assigned at random.

**Comment by propstg** [comment]
Hey, thanks for the suggestions. I'll try to get to them soon.

**Comment by propstg** [comment]
Hey, @jwbjnwolf, could I get your route config, please? Thanks!

**Comment by jwbjnwolf** [comment]
Here's a map of my routes. I haven't actually created them themselves with this, I'm going through the process of getting the coords of all the places I use as bus stops. Hopefully this makes sense for you. Got plenty of routes on it.

https://drive.google.com/folderview?id=1OaOyseVTpA_ZjZz0PbadoW05lHLfxoQy

**Comment by propstg** [comment]
Thanks! That looks cool.

I added the ability to have different end points. You can set `BusReturnPoint` in the route's config to control where to drive the bus to despawn it and end the route.

I haven't decided how to implement the other part of the request, yet. I'll think about it and try to get to it soonish.

**Comment by jwbjnwolf** [comment]
You are a legend, well that's my weekend make!!

**Comment by propstg** [comment]
Thanks for changing the title (and being so responsive!). And that'd be great! :D

I made a change for the route selection. Single-line routes will continue to just start the route, like normal. If there's more than one line, a menu like this should be displayed:

![blarglebus-select-route](https://user-images.githubusercontent.com/22607691/73116222-a17b8c80-3f00-11ea-966c-38ac93fb86b8.png)

**Comment by jwbjnwolf** [comment]
Absolutely amazing! At least now there won't be so many blips especially at the Dashound bus center!

**Comment by jwbjnwolf** [comment]
Only last thing that would be sweet is if there is at all any way to get the passengers entering/leaving the bus properly. But I won't add that as an issue as that doesn't bother me and I'm sure there's some kind of awkward game native scripting you need to work out to do that. Thank you a lot! :)

**Comment by propstg** [comment]
No problem! Let me know if you have any issues with the changes.

I think I know what you mean about the passengers leaving the bus, but could you explain what you're looking for a little more? Thanks!

**Comment by jwbjnwolf** [comment]
As it is right now the passengers spawn inside and then outside of the bus both sides rather than actually using the entrance and exit doors like how you obviously would in reality. If you look at videos shown on the LSTransit Bus Mod GTA5-Mods page for single player, that shows the passengers entering/exiting the bus properly.

**Comment by jwbjnwolf** [comment]
Ok I've noticed two slight troubles with the bus line grouping method for having the menu.

The Menu works perfectly, setting the end point works perfectly,

However, you have to set the bus model and the end point in the route. You cannot do so in the line, so firstly I can only have one kind of bus for every route grouped in the route lines, and the end location has to be the same for every line.

So that takes me back to having individual blips for each route as it's own separate thing.

So if you are able to change it so you instead set the bus model and end point for each individual line, then that'd be great.

I know that means a little bit of repeated code when it's the same bus/end point being used like the metro lines, however will definitely help sort out that I want the 70, 72 and 82, all Paleto Buzz routes that start from Dashound, but one ends in Vinewood hills rather than at Paleto, and I intend on the 82 using a double decker bus instead of a single decker.

So for a quick example to make it more clear:

> BusRoute = {
   Name = 'bus_route',
   **~~BusModel = 'bus',~~**
   ...
   **~~BusReturnPoint = { x = X.XX, y = X.XX, z = X.XX heading = X.XX},~~**
   ...
   lines = {
   Name = 'Bus Line 1',
   **BusModel = 'bus",
   BusReturnPoint = { x = X.XX, y = X.XX, z = X.XX heading = X.XX}**,
   ... }
   Name = 'Bus Line 2',
   **BusModel = 'bus2",
   BusReturnPoint = { x = -X.XX, y = -X.XX, z = -X.XX heading = -X.XX}**,
   ... }
}

Hopefully you understand that :)

**Comment by propstg** [comment]
Heya, I've made a pull request that I think should allow what you're going for, but slightly differently. 

The variables that would need to be overridden to change a bus are BusModel, Capacity, Doors, and FirstSeat. To avoid copying and pasting those everywhere, I pulled the bus configs out into config/BusType.lua. So a route can now just have Bus = BusType.CityBus (or DoubleDecker, or whatever).

To try to keep the config backwards compatible, I kept the bus information and return point on the route. These will be treated as a default for all lines on the route. Individual lines can have these two properties set to override the default: `BusOverride` and `BusReturnPointOverride`.

If you can, please take a look at https://github.com/propstg/esx-blarglebus/pull/16 and let me know if you think that will work for you.

Thanks!

**Comment by propstg** [comment]
@jwbjnwolf I went ahead and merged that branch. Let me know if you have any issues with it. Thanks!
