### ISSUE TITLE
Server hitch warnings over 1000miliseconds !!

### ISSUE THREAD

**Issue by Tinky124** [propstg/esx-blarglebus#17]
So when players do same job like 3-4 players working at same moment job, too many npc will spawned and cause in server console lagg and server hitch warning if it is possible do fix that?

**Comment by propstg** [comment]
Hmm, I'm not 100% sure, as I haven't had that issue (and I'm at work, so I can't play around with it).

Two possible fixes:
1. Lower the bus capacity in the route configs, so less NPCs spawn
2. Make the peds not synced. I think this means they'll only appear on the driver's screen, but that might not be a bad thing. 
To do that, change line 11 in `client/peds.lua` from this :
```
local ped = CreatePed(4, modelName, x, y, coords.z, heading, true, false)
```
To this:
```
local ped = CreatePed(4, modelName, x, y, coords.z, heading, false, false)
```

**Comment by Tinky124** [comment]
@propstg Very nice dude thank you it fixed issuse with step 2. :)!! Closing Issue

**Comment by propstg** [comment]
@Tinky124 Great, thank you for trying it out! I'll add a config option for it when I get a chance.

**Comment by propstg** [comment]
@Tinky124 I merged a change to make this a config option, Config.OnlyShowPedsOnClient (defaulted to true). Thanks for bringing this to my attention!
