### ISSUE TITLE
request

### ISSUE THREAD

**Issue by oogienl** [propstg/esx-blarglebus#19]
first of all thanks for making this great resource! I am wondering if it is somehow possible to make trigger events possible at every stop, as in, id like to execute audio files from another resource to play at every stop telling them the current location and the next stop, no idea if this would be hard to do or not, for me atleast would be impossible to figure out. hopefully there would be a way please let me know thank you  - oogie

**Comment by propstg** [comment]
Hey, that sounds like an interesting idea.

Just to clarify, by "from another resource", does that mean that the only change to this resource would be to emit the event with the current and next stop, and that you already have another resource that would listen for the event and play audio?

**Comment by oogienl** [comment]
that is correct, you already made it easy to create custom routes, i have another resource handling the audio. All that is needed is a place in the script to be able to trigger events at bus stops

**Comment by propstg** [comment]
Hey,

Awesome, that should be easy, then.

Will something like this work (handlers put in your other resource)? In this example, the name passed to the function would be the localized stop name that's displayed on the overlay and the notifications.

```
AddEventHandler('blarglebus:arrivedAtStop', function(stopName)
    print('in arrived at stop handler')
    print(stopName)
end)

AddEventHandler('blarglebus:departingStop', function(nextStopName)
    print('in departing stop handler')
    print(nextStopName)
end)
```

**Comment by oogienl** [comment]
lets have a chat sometime if you want, it feels like i could explain it much better thatway Oogie#5465

**Comment by propstg** [comment]
Are you trying to integrate with a public resource that I could look at?

Or, how do you need the event structured to work with it?

**Comment by oogienl** [comment]
thank you for helping me out

**Comment by propstg** [comment]
No problem!
