### ISSUE TITLE
Client Crash upon starting Job

### ISSUE THREAD

**Issue by Avanae** [propstg/esx-blarglebus#31]
I run a Windows OneSync server, upon starting a route, the game crashes with florida-fanta-snake, this happens on all routes during "Wait for passengers to finish loading"

**Comment by propstg** [comment]
Hey, thanks for the report. What server version are you using?

**Comment by Avanae** [comment]
I run the latest server artifact, however I found out a custom model was causing the issue. However the custom vehicle in question has the same amount of seats as the regular default bus, however upon reverting back to the old bus, the plugin seems to function.

**Comment by Avanae** [comment]
Although now I'm running into the same issue of the guy still openend about crashing when you exit the bus. And I remove the Loop suggestion about notifying people to get out of the bus.

**Comment by Tinky124** [comment]
Windows OneSync server like i said something is problem with onesync @propstg

**Comment by Tinky124** [comment]
i think this is duplicate issue of #29

**Comment by Morfiiii** [comment]
I have the same problem.
I added a custom bus with 1 front door and 2 back doors.
When I start the job the bus spawns in, when I stop at the first stop.
I get a fivem crash. With the regular GTAV bus it works, but not with the added bus.

**Comment by propstg** [comment]
Did you change the doors in the config? Based on this comment, it looks like getting the door numbers wrong can cause a crash: https://github.com/propstg/esx-blarglebus/issues/8#issuecomment-505477156

**Comment by Avanae** [comment]
I'm running the plugin fully stock, with the stock GTA V bus. It will crash on every route, with any vehicle. Not just the bus but the airport one too as soon as you step out of a vehicle during your route.

**Comment by propstg** [comment]
That was meant for @Morfiiii, because they said they are only crashing with a custom bus.

**Comment by Avanae** [comment]
Ahh my bad. I got a notification from it 😂😂

**Comment by propstg** [comment]
No worries. Unfortunately I haven't really had time to look into your issue more. I'll try to make some time to give it another look.

**Comment by Morfiiii** [comment]
> Did you change the doors in the config? Based on this comment, it looks like getting the door numbers wrong can cause a crash: [#8 (comment)](https://github.com/propstg/esx-blarglebus/issues/8#issuecomment-505477156)

The problem was indeed with the doors :) Now it works!

Thanks!

**Comment by propstg** [comment]
I'm going to close this, as the original issue is resolved and the remaining issue is a duplicate. I've updated the readme with more detailed information on adding custom buses to help avoid the original issue, in the future. Not sure if there will be any timely updates on #29, but please check there for updates on that issue.
