### ISSUE TITLE
Request Disable Spawn Ped

### ISSUE THREAD

**Issue by gerung** [propstg/esx-blarglebus#32]
How to disable spawn peds, cause this make the server is down, thanks :-)

**Comment by propstg** [comment]
Hey,

I _think_ you should be able to change Capacity to 0 for all the vehicles in https://github.com/propstg/esx-blarglebus/blob/master/config/busType.lua to prevent any peds from spawning. 

Let me know if that doesn't work. 

Thanks!

**Comment by koisine** [comment]
Thank for update,

Doesn't work, the notifications that appear there are no passengers and can't continue to next station. I getting an error on client/main.lua:447
![image](https://user-images.githubusercontent.com/64629964/82924740-f9a5c680-9fa6-11ea-932a-83c321dd4821.png)

Thanks

**Comment by propstg** [comment]
Hmm, might have to change all of the `UnloadType.Some` in the config/routes files to `UnloadType.All`, to work around that error. I don't see anything in the setup function for all that should break on 0 peds, but I am unable to test it out, right now.

**Comment by koisine** [comment]
I change minimumDepartingPeds and math.random to '0' on client line #447
```
local numberOfPedsToSpawn = math.random(0, busType.Capacity)
local minimumDepartingPeds = 0
```
and working, but how to configure to get the money from each terminal even though there are no passengers?

**Comment by propstg** [comment]
Ah, yeah, I suppose that'd be easier. 

The route should pay a fixed amount at the end (based on the route config), even with no passengers.

If you want a fixed amount paid at every stop as well, you could change the payForEachPedLoaded function to skip the > 0 check and set amountToPay to that amount.

```
function payForEachPedLoaded(numberOfPeds)
    local amountToPay = 999
    TriggerServerEvent('blarglebus:passengersLoaded', amountToPay)
    ESX.ShowNotification(_U('passengers_loaded', numberOfPeds, amountToPay))
    totalMoneyPaidThisRoute = totalMoneyPaidThisRoute + amountToPay
end
```

**Comment by koisine** [comment]
Thanks for the update

That's working, thanks and i appreciate you

**Comment by NikolaiSlayOlai** [comment]
im not working dude function payForEachPedLoaded(numberOfPeds)
    local amountToPay = 999
    TriggerServerEvent('blarglebus:passengersLoaded', amountToPay)
    ESX.ShowNotification(_U('passengers_loaded', numberOfPeds, amountToPay))
    totalMoneyPaidThisRoute = totalMoneyPaidThisRoute + amountToPay
end 



where this should i put this script?

**Comment by elsiervodedios01** [comment]
hello I have a problem with the bus work the passengers do not appear

**Comment by propstg** [comment]
@elsiervodedios01 Hi. Please create a new issue to track your problem.

**Comment by propstg** [comment]
@NikolaiSlayOlai & @gerung,

I added a couple config options to allow this. With the latest master commit, setting `Config.SpawnPeds = false` should prevent the peds from spawning. Additionally, the setting `Config.MoneyPerStopNoPedsOverride` controls how much money is awarded to the player, per stop, in this scenario.

Please let me know if you have any issues with this.
