### ISSUE TITLE
Start Job

### ISSUE THREAD

**Issue by Ivan02111** [propstg/esx-blarglebus#33]
I know it sounds very dumb, maybe i am where can i start the job i didnt see any line about it...

**Comment by propstg** [comment]
You need to have the busdriver job selected as your job to use it. Once you have it selected, there should be blips on your map showing the start locations. 

There are three start points for the default routes:
* Airport shuttle route starts near the airport.
* LS metro starts at the Strawberry station under the highway.
* Scenic route starts at the Dashound Bus Center in Los Santos.

Their specific spawn locations are defined in each of the files in the config/routes directory, under the "SpawnPoint" option.
