### ISSUE TITLE
[BUG] Wrong language displayed

### ISSUE THREAD

**Issue by biskfather** [propstg/esx-blarglebus#39]
mot so much a bug but how can i change the script into english as all text is in adeifferent language and i dont know what to do.
i have changed config locale to en. 
what else can i do

**Comment by propstg** [comment]
Hi @biskfather,

Strange. It should show english by default. Could you share your config.lua file, please?

Thanks!

**Comment by propstg** [comment]
Actually, I confused this script with another one. This script doesn't have any language files other than english, at the moment, so this seems like this should be impossible?

Do you have a screenshot of this script displaying text in a different language?

**Comment by biskfather** [comment]
Hi, yes I will get a screenshot today

dgmasters
01843216168
07305035265
flat 1
21 rosedale road
margate
ct9 2td

**Comment by biskfather** [comment]
![2021 03 14-13 27](https://user-images.githubusercontent.com/80595080/111070325-2f318700-84c9-11eb-9c2e-e5960d794bb1.png)
![2021 03 14-13 27_01](https://user-images.githubusercontent.com/80595080/111070328-322c7780-84c9-11eb-97e4-59d514de7189.png)

there you go

**Comment by propstg** [comment]
Google Translate suggests that might be Turkish, lol.

1. Did you get the script from pulling from this repo? Or did you get it somewhere else? I see that https://github.com/rowsey-chris/HellFireRP has a copy of my script, for instance, and it has some non-english words in the en.lua file (the translations don't line up 100% with what you're seeing, but I found it by searching for some of the words in your screenshot).

2. What does your `locales/en.lua` file look like?

3. Are there any other files in `locales/`?

4. I'm not sure if they even exist, but do you have any scripts that might automatically translate text from other scripts (or anything that might be overriding the ESX translate function)?

**Comment by biskfather** [comment]
Want me to send the files to you?

**Comment by propstg** [comment]
Yes.

**Comment by biskfather** [comment]
wont let me send a .lua or a folder

**Comment by propstg** [comment]
Open it and copy the contents

**Comment by biskfather** [comment]
Locales['en'] = {
    ['route_assigned']                      = 'Yeni Rota: ~g~%s~s~.',
    ['drive_to_first_marker']               = 'Otobüse Bin ve İlk Durağa Sür ~g~%s~.',
    ['drive_to_next_marker']                = 'Sonraki Durağa Sür : ~g~%s~.',
    ['no_passengers_loading_or_unloading']  = 'Burada İnmek İstiyen veya Binmek İstiyen Yolcu Yok..',
    ['no_passengers_unloading']             = 'Yolcuların Binmesini Bekle..',
    ['no_passengers_loading']               = 'Yolcuların İnmesini Bekle... Bu Durakta Binmeyi Bekliyen Yolcu Yok..',
    ['wait_for_passengers']                 = 'Yolcuların İnmesini ve Binmesini Bekle..',

    ['start_route']                         = 'İse Baslamak İçin ~INPUT_PICKUP~ Tuşuna Basınız ~g~%s~.',
    ['passengers_loaded']                   = '~g~%d~s~ Yolcular Bu Durak İçin Ödeme Yaptı,  ~g~$%d. Kazanıldı',
    ['return_to_terminal']                  = 'Tüm Rotalar Tamamlandı. İstasyona Geri Dön...',
    ['stop_bus']                            = 'Ödemeni Almak için Otobüsü Durdur...',
    ['abort_route_help']                    = 'İşin İptal Etmek İçin ~INPUT_PICKUP~ Tuşuna Bas...  ~r~$%d. Ödiyeceksin..',

    ['next_stop_label']                     = 'Sonraki Durak',
    ['money_earned_label']                  = 'Elde Edilen Para',
    ['stops_remaining_label']               = 'Kalan Rota',

    ['abort_route']                         = 'iptal Et ~g~%s',
    ['airport_route']                       = 'Havayolu Otobüs Şöförlüğü',
    ['scenic_route']                        = 'Los Santos Otobüs Şöförlüğü',
    ['metro_route']                         = 'Şehir İçin Otobüs Şöförlüğü',
    ['metro_yellow']                        = 'Metro Sarı Hat',
    ['metro_blue']                          = 'Metro Mavi Hat',
    ['metro_red']                           = 'Metro Kırmızı Hat',
    ['metro_purple']                        = 'Metro Mor Hat',
    ['metro_orange']                        = 'Metro Doğu',
    ['metro_black']                         = 'Metro Batı',
    ['terminal']                            = 'Terminal',

    ['stop_banner_hotel']                   = 'Poet Otel ve Masaj Tesisleri',
    ['stop_von_crastenburg']                = 'Sakarya Mahallesi',
    ['stop_airport']                        = 'Havalimanı',
    ['stop_elgin']                          = 'Roman Mahallesi',
    ['stop_venetian']                       = 'Boşnak Mahallesi',
    ['stop_viceroy']                        = 'Çerkez Mahallesi',
    ['stop_crastenburg']                    = 'Laz Mahallesi',
    ['stop_opium_nights']                   = 'Tütün Mahallesi',
 
    ['stop_dashound']                       = 'Otobüs Merkezi',
    ['stop_banham_canyon']                  = 'Yusuflu Durağı',
    ['stop_lago_zancudo']                   = 'Ataberkler Durağı',
    ['stop_north_chumash']                  = 'Çağdaş Durağı',
    ['stop_chiliad']                        = 'Enesler Durağı',
    ['stop_paleto_bay']                     = 'Erenler Durağı',
    ['stop_grapeseed']                      = 'Erdemler Durağı',
    ['stop_sandy_shores']                   = 'Salihler Durağı',
    ['stop_senora_park']                    = 'Sezerler Durağı',
    ['stop_harmony']                        = 'Emir Durağı',

    ['stop_metro_station_departures']       = 'Bu Durak',
    ['stop_metro_station_arrivals']         = 'Durak',
    ['stop_metro_vespucci_sinner']          = 'Slime Sokağı',
    ['stop_metro_popular']                  = 'Vatan Roleplay  Sokağı',
    ['stop_metro_hawick_meteor']            = 'Hawick Ave / Meteor St',
    ['stop_metro_hawick_alta']              = 'Hawick Ave / Alta Pl',
    ['stop_metro_strawberry_ave']           = 'Strawberry Ave',
    ['stop_metro_peaceful_san_andreas']     = 'Peaceful St / San Andreas Blvd',
    ['stop_metro_vespucci_alta']            = 'Vespucci Blvd / Alta St',
    ['stop_metro_peaceful_vespucci']        = 'Peaceful St / Vespucci Blvd',
    ['stop_metro_business_center']          = 'Arcadius Business Center',
    ['stop_metro_rockford_plaza']           = 'Rockford Plaza',

    ['stop_metro_carcer_way']               = 'Carcer Way',
    ['stop_metro_rockford_eastbourne']      = 'Rockford Dr / Eastbourne Way',
    ['stop_metro_delperro_madwayne']        = 'Del Perro Blvd / Mad Wayne Thunder Dr',
    ['stop_metro_dorset_palomino']          = 'Dorset Dr / Palomino Ave',
    ['stop_metro_sanandreas_calais']        = 'San Andreas Ave / Calais Ave',
    ['stop_metro_vespucci_ginger']          = 'Vespucci Blvd / Ginger St',
    ['stop_metro_ginger']                   = 'Ginger St',
    ['stop_metro_sanandreas_ginger']        = 'San Andreas Ave / Ginger St',
    ['stop_metro_alta_gruppe']              = 'Alta St at Gruppe Sechs',
    ['stop_metro_fib']                      = 'San Andreas Ave at FIB',
    ['stop_metro_delperro_rockford']        = 'Del Perro Blvd / Rockford Dr',
    ['stop_metro_delperro_morningwood']     = 'Del Perro Blvd / Morningwood Blvd',
    ['stop_metro_delperro_plaza']           = 'Del Perro Plaza',
    ['stop_metro_marathon_baycity']         = 'Marathon Ave / Bay City Ave',
    ['stop_metro_vespucci_elgin']           = 'Vespucci Blvd / Elgin Ave',
    ['stop_metro_marathon_prosperity']      = 'Marathon Ave / Properity St',
    ['stop_metro_eclipse_cougar']           = 'W Eclipse Blvd / Cougar Ave',
    ['stop_metro_marathon']                 = 'Marathon Ave',
}
thats the locales/en.lua

**Comment by propstg** [comment]
If you didn't make these changes yourself, then you must have downloaded a modified version of this script from somewhere else. Try with a fresh copy directly from this repo.

**Comment by biskfather** [comment]
will try that, thanks
