### ISSUE TITLE
[BUG] i don't see the bus

### ISSUE THREAD

**Issue by ClaudiuCitar** [propstg/esx-blarglebus#41]
**Describe the bug**
I don't see the bus, i start the resource but all the map don't have any bus.
I have npc disambled.
**To Reproduce**
I start the server with ensure and resource in server.cfg, and i don't see the bus on the map.. (on the routes).

**Likely essential information**
1. Are there any errors in the server console?: No.

2. Are you using OneSync? (Note: This mod probably does not work with OneSync and I have been unable to really reproduce any of the issues.): No, i use vSync. 

3. What server version are you using?: Latest.

4. If the player's game is crashing, is there an error message displayed to the player when the game crashes?: don't see bus.

5. Does the issue only happen occasionally? or every time?: Every time

6. Is there a particular route that the issue happens on? or is it all routes?: Public routes from script.

7. Are you using a custom route/bus?: no

**Screenshots**
If applicable, add screenshots to help explain your problem. Can be screenshots of errors in console.

**Additional context**

**Comment by propstg** [comment]
Are you saying the bus icons are not showing up on the pause screen map?

Or that you can't find a bus in the actual world?

**Comment by ClaudiuCitar** [comment]
> Are you saying the bus icons are not showing up on the pause screen map?
> 
> Or that you can't find a bus in the actual world?

I don't see the bus anywhere on the map or the bus icon. And the resource is on.

**Comment by propstg** [comment]
Do you have the "busdriver" job selected?

**Comment by ClaudiuCitar** [comment]
This script is not for NPC? A NPC with bus?

**Comment by propstg** [comment]
No... PC bus driver, NPC passengers.

**Comment by ClaudiuCitar** [comment]
Oh... :(
And how i can get the busdriver job if i have esx_jobs?

**Comment by propstg** [comment]
Run the `localization/en.sql` script to add the job to your database and then select the job with a script like https://github.com/esx-framework/esx_joblisting.
