### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dildarfreak2** [propstg/esx-blarglebus#42]
Dont start it up .
and yes i write the right in my server.cfg
i use esx 1.2

i use one sync

he show me not any error in my console

**Comment by propstg** [comment]
Weird. If you're not getting any errors, and if you claim the server.cfg is correct, then can you check the following? I think either one of these would probably start without errors but prevent you from using it.

1. Did you run this SQL to add the busdriver job to your database? https://github.com/propstg/esx-blarglebus/blob/master/localization/en.sql
2. Do you have the busdriver job selected for your character?
