### ISSUE TITLE
TRAIN JOB (Blarglebus + TrainSportation)

### ISSUE THREAD

**Issue by AgustinRonsvalle** [propstg/esx-blarglebus#43]
Hello, I want to congratulate you for the excellent job.
I was using it and it seemed like a very good idea to be able to join it to the "TrainSportation" resource and thus be able to make train stops where the NPCs board.
I have been trying with your script but I can't get that instead of creating a bus, it recognizes the train as the vehicle to use.

I think that by somehow modifying this function found in "bus.lua" it could be done.

function Bus.CreateBus(coords, model, color)
    ESX.Game.SpawnVehicle(model, coords, coords.heading, function(createdBus)
        Bus.bus = createdBus
        Bus.plate = string.format('BLARG%03d', math.random(0, 999))
        SetVehicleNumberPlateText(Bus.bus, Bus.plate)
        SetVehicleColours(Bus.bus, color, color)
        Bus.PutPlayerInBusIfNeeded()
        Bus.WaitForFirstEntryAndFillTankIfNeededAsync()
    end)
end

I think the solution is that the resource recognizes that there is a train nearby and takes it as a vehicle to carry out the mission.

I leave you the link of the resource to which I refer:
https://forum.cfx.re/t/release-trainsportation-drive-be-a-passenger-in-a-train/52179

I would be very grateful if you could take this into account and do it or give me a guide on this path, I have tried a lot and I can't think of what else to try.

Greetings

**Comment by propstg** [comment]
Hi @GeneralBondi; thanks.

That sounds like a cool idea. I don't currently have FiveM installed (or in my head), so I don't have any quick answers. I vaguely remember trying that resource out a while ago and not having much luck with it, so hopefully that's changed.

I'll try to take a look at this soonish and get back to you.

Thanks!

**Comment by AgustinRonsvalle** [comment]
Hello propstg, first of all I wanted to thank you for the time in answering me, the truth is that I am getting into this programming thing and there are many things that I still don't know how to do, I would have liked to be able to solve the problems on my own and come with everything finished .I thank you very much, I will be sending you a video of what I have been able to achieve so you have some reference. Big hug

**Comment by propstg** [comment]
Definitely appreciate that you've taken a crack at it yourself. A video might be interesting!
