### ISSUE TITLE
[BUG] sql issue

### ISSUE THREAD

**Issue by Alyxiate** [propstg/esx-blarglebus#44]
**Describe the bug**
sql file says INSERT INTO `jobs` (name, label) VALUES	('busdriver', 'Bus Driver'); #1146 - Table 'essentialmode.jobs' doesn't exist when i try to import it

**To Reproduce**
Detailed steps to reproduce the behavior. import sql into mysql using xampp or heidisql

**Likely essential information**
1. Are there any errors in the server console? no

2. Are you using OneSync? (Note: This mod probably does not work with OneSync and I have been unable to really reproduce any of the issues.) no

3. What server version are you using? legacy 1.10.5

4. If the player's game is crashing, is there an error message displayed to the player when the game crashes? no

5. Does the issue only happen occasionally? or every time? every time

6. Is there a particular route that the issue happens on? or is it all routes? no

7. Are you using a custom route/bus? no

**Screenshots**
If applicable, add screenshots to help explain your problem. Can be screenshots of errors in console.
![image](https://github.com/propstg/esx-blarglebus/assets/118795368/ddbde3f1-6ca5-4357-897b-908e2d89c8f4)
![image](https://github.com/propstg/esx-blarglebus/assets/118795368/2859118a-2b4c-4783-ac3b-675f2dc5083b)

**Additional context**

**Comment by propstg** [comment]
Heya. A few quick questions:

1. Do you have esx installed and do other job mods work with it?
2. If it's installed, where did you install it from? (It's possible this mod is just out of date, but idk)
3. Is your essentialmode schema named something else?

**Comment by propstg** [comment]
Actually, looking closer at your second screenshot, is your essentialmode schema named `esxlegacy_495591`? Might be worth trying again, with ``USE `esxlegacy_495591`;`` instead of ``USE `essentialmode`;``

**Comment by Alyxiate** [comment]
that worked thanks
