### ISSUE TITLE
[BUG]GPS and routes not working on custom route

### ISSUE THREAD

**Issue by Alyxiate** [propstg/esx-blarglebus#48]
**Describe the bug**
A clear and concise description of what the bug is. GPS and stops not showing on custom route

**To Reproduce**
Detailed steps to reproduce the behavior. made a custom route

**Likely essential information**
1. Are there any errors in the server console? no

2. Are you using OneSync? (Note: This mod probably does not work with OneSync and I have been unable to really reproduce any of the issues.) no

3. What server version are you using?legacy 1.10.5

4. If the player's game is crashing, is there an error message displayed to the player when the game crashes?no

5. Does the issue only happen occasionally? or every time? every time

6. Is there a particular route that the issue happens on? or is it all routes? custom route

7. Are you using a custom route/bus?yes

**Screenshots**
If applicable, add screenshots to help explain your problem. Can be screenshots of errors in console.
![image](https://github.com/propstg/esx-blarglebus/assets/118795368/4da15cce-5032-4ad8-b01a-3607053a90bd)
![image](https://github.com/propstg/esx-blarglebus/assets/118795368/82ca34b8-a1cd-47b1-a1bf-d35ba1583f1f)

**Additional context**

**Comment by Alyxiate** [comment]
oh, turns out i do have onesync on, but my server wont run without it

**Comment by propstg** [comment]
Hmm. Could I get a copy of this mod's config files and a log file from your server?

**Comment by Alyxiate** [comment]
[fxserver_1716620544.log](https://github.com/propstg/esx-blarglebus/files/15442091/fxserver_1716620544.log)
[config.txt](https://github.com/propstg/esx-blarglebus/files/15442096/config.txt)
[metroreplacement.txt](https://github.com/propstg/esx-blarglebus/files/15442097/metroreplacement.txt)
had to upload the lua files as .txt because github wouldnt let me send lua

**Comment by propstg** [comment]
Thanks. Sorry for the delay in getting back to this.

I don't see any errors that look relevant in the server logs. Would it be possible to get a copy of your client logs, after you try to start the route?

Were the new stop names added to the `locales/en.lua` file?
