### ISSUE TITLE
compatibility with Legacyfuel

### ISSUE THREAD

**Issue by shyricaus** [propstg/esx-blarglebus#5]
could it be compatible with legacy fuel

**Comment by shyricaus** [comment]
Your script is beautiful, know it.

**Comment by propstg** [comment]
Hey, thank you for the kind words and suggestion!

All that the FrFuel support does is set the initial bus fuel to 100%, so I'm assuming that's what you're looking for.

I added a flag to config.lua: Config.UseLegacyFuel. Pull/download the latest changes and set it to true to enable it.

Let me know if this isn't quite what you were looking for or if you have any other suggestions.

Thanks!
Gregory

**Comment by m4drid88** [comment]
Hi. It wasnt work for me. So i use the exports available in Legacy Fuel. I add
function Bus.WaitForFirstEntryAndFillTankIfNeededAsync()
    if Config.UseLegacyFuel then
        **exports["LegacyFuel"]:SetFuel(Bus.bus, 100)**
    elseif Config.UseFrFuel then
        Bus.DoFillForFrFuel()
    end
end

Your script is awesome. Thanks!

**Comment by propstg** [comment]
Thanks for the heads up! I'll take a look when I get a chance. I'm probably using an old version of legacy fuel or something on my server. :)

**Comment by propstg** [comment]
It turns out that I _was_ running an old version of the LegacyFuel script. I've merged a change that should support how it works now and how it worked in the old version. Let me know if you have any issues with it.

Thanks again, @m4drid88!
