### ISSUE TITLE
Metro route: People not loading on first stop

### ISSUE THREAD

**Issue by BradHex** [propstg/esx-blarglebus#8]
Been using this script for a while and I came to do the metro route, when on the first stop the passengers just stand there looking at the bus and will refuse to move. I have played around with some configs on the route to see if this fixed the issue and sadly it does not. 

Sometimes the passengers will load it's just a 50/50 chance at the moment. Thanks.

**Comment by propstg** [comment]
Hey, thanks for the report, sorry to hear you're having a problem with it. I just tried about 10 times and, unfortunately, wasn't able to recreate this on my server.

1. Are you seeing any errors in the F8 log?
2. Could you set `Config.DebugLog = true` and attach a screenshot of the log when it happens again?
3. Are you seeing the "Wait for passengers to finish loading" notification when you pull up next to the stop?
4. Is it a particular route that is giving you problems, or does it happen with all of them? (There should be a "You have been assigned..." notification that says which specific route it is, when you start the metro route)

**Comment by BradHex** [comment]
F8 Console displays no errors that was the first thing I checked.

The notification does appear not an issue on that side. 

The rest of the routes are fully functional and are great. I'll turn on the debug when I get home tonight and I'll provide more details.

**Comment by BradHex** [comment]
So.. 

DEBUG LOG:
'next stop is All, all peds should unload, should spawn peds equal to capacity'

then it loads the ped names etc.

This is all I get, the peds just standing there. Might just be me aha!

![download (1)](https://user-images.githubusercontent.com/39734135/56434716-aa826200-62cd-11e9-99fb-be1d1234fe20.jpg)

**Comment by propstg** [comment]
> Might just be me aha!

Haha, well, if it makes you feel better, I've been carjacked by spawned peds before while testing and had to chase my own bus down. :P

Anyway, I really appreciate your appreciation (and patience!) in looking into this. If you don't mind helping a bit more, I made a branch (`what-the-heck`) that adds a bit more logging, to see if maybe it's getting stuck somewhere. It might be a bit spammy, so the CitizenFX.log file might be more informative than a screenshot. If you see anywhere where additional logging might make sense, feel free to add it.

Thanks!

**Comment by BradHex** [comment]
Peds stealing buses sounds like a challenge 😆

It's not an issue, i'd rather help figure this out! and I will post as much detail as I can.

Okay man, I will throw it on my dev server when I get a free hour and see what the case is.

**Comment by subtraho** [comment]
Hey,

im having the same problem but i think i know what's the error (also im using an addon bus)
my addon bus lets fivem chrash when all doors are opened and the peds have to go into the bus. my addon bus only has 3 doors which do really open (left front, left back, right back). when i change the doors in the script it works but some peds keep standing at the stop and dont do anything. 

What im trying to say is. are peds locked to certain doors or something because when i put another addon bus on the route that can open all 4 of the doors it works fine. And is this fixable??

**Comment by propstg** [comment]
Heya,

Thanks for the information!

The peds are assigned the first available seat up to the "Capacity" (in the config) for the bus, and the game decides how they get there, so the difference in doors shouldn't cause an issue with the peds loading.

Which add on bus are you using? Is it always the same number of peds standing around, after the rest load? If so, my guess would be that the add on bus has fewer actual seats than the original bus, which would prevent all of them from boarding. You may need to lower the Capacity for the route that you're using that bus on.

**Comment by subtraho** [comment]
Hey,

im using this bus: https://nl.gta5-mods.com/vehicles/vdl-berkhof-ambassador-connexxion-dutch-nederlands

with this skin: https://nl.gta5-mods.com/paintjobs/vdl-arriva-tilburg 

this bus chrashed my fivem game when the peds were getting into it after opening all the doors. But when i changed the doors in the config file one of the backdoors didn't open (so the game didn't chrash when peds were trying to get in) but 2 peds would always stand still.

All the stops worked fine with this bus except for the first stop. 2 people wouldnt get into the bus. I figured there was to little capacity in the bus and tried to increase the number which didn't work. but youre saying i should lower the number?

**Comment by propstg** [comment]
Heya, thanks! I can try that bus out when I get a chance just to confirm, but the capacity in the config is just the number of actual seats on the bus (not including the driver). The first stop spawns that many peds, so the bus starts off full. If two are left out, that _probably_ means the bus only has 14 seats (the default has 16), so you might try lowering the capacity to 13.

**Comment by subtraho** [comment]
allright thanks ill try it

**Comment by subtraho** [comment]
Hey man,

ur solution worked! i still had to change the door configuration though as else my fivem would chrash but i dont mind that at all! 

Thanks for the amazing support!

**Comment by Avanae** [comment]
I'm running the plugin fully stock, with the stock GTA V bus. It will crash on every route, with any vehicle. Not just the bus but the airport one too as soon as you step out of a vehicle during your route.
