### ISSUE TITLE
Can you spawn directly into the driver seat of the bus

### ISSUE THREAD

**Issue by subtraho** [propstg/esx-blarglebus#9]
Hey,

is there a way to put in the script that when the bus spawns you automatically sit into the drivers seat?

i have a script that won't allow npc vehicle stealing but i also can't take this bus then.

thanks, 
-subtraho

**Comment by m4drid88** [comment]
Hi. Im a noob but i add this in \client\bus.lua
function Bus.CreateBus(coords, model, color)
    ESX.Game.SpawnVehicle(model, coords, coords.heading, function(createdBus)
        Bus.bus = createdBus
        Bus.plate = string.format('BLARG%03d', math.random(0, 999))
        **player = GetPlayerPed(-1)**
        SetVehicleNumberPlateText(Bus.bus, Bus.plate)
        **SetPedIntoVehicle(player, Bus.bus, -1)**
        SetVehicleColours(Bus.bus, color, color)
        Bus.WaitForFirstEntryAndFillTankIfNeededAsync()
    end)
end

it works, but i dont know yet if i'll get a bug later.

i hope it helps you.

**Comment by propstg** [comment]
Thanks @m4drid88, that looks like it should be fine. I'll add it behind a config option when I have a moment.

**Comment by subtraho** [comment]
hey @m4drid88,
your solution worked in my case, thank u very much!

-subtraho

**Comment by propstg** [comment]
Awesome, thanks again @m4drid88! I appreciate it.

I merged a change to support this. If you pull the latest changes, you can set `Config.PutPlayerInBusOnSpawn = true` to make it happen. (The default is false, to maintain the current functionality.)
